# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('package', models.CharField(max_length=44, null=True)),
                ('timesUsed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_uuid', models.CharField(max_length=44)),
                ('project_workflow', models.TextField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('lastModificationDate', models.DateTimeField(default=datetime.datetime.now)),
                ('client_ip', models.GenericIPAddressField(null=True)),
                ('timesModified', models.IntegerField(default=0)),
            ],
        ),
    ]
