# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddressBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='client_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='client_city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='client_country',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
