# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='json',
        ),
        migrations.AddField(
            model_name='workflow',
            name='jsonString',
            field=models.TextField(null=True),
        ),
    ]
