# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressblacklist',
            name='client_ip',
            field=models.GenericIPAddressField(null=True, unique=True),
        ),
    ]
