# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0002_auto_20170719_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='protocol',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_protocols.Package'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocolType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_protocols.ProtocolType'),
        ),
    ]
