# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0002_auto_20161117_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='jsonString',
            new_name='json',
        ),
    ]
