# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0003_auto_20161117_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='hash',
            new_name='project_uuid',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='json',
            new_name='project_workflow',
        ),
    ]
