# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0004_auto_20180116_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pipName',
            field=models.CharField(blank=True, default='', help_text='name of the plugin in pip repository', max_length=256),
        ),
    ]
