# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0004_auto_20161117_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='client_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='timesModified',
            field=models.IntegerField(default=0),
        ),
    ]
