# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0006_auto_20161120_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocol',
            options={},
        ),
        migrations.AddField(
            model_name='workflow',
            name='lastModificationDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
