# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0006_auto_20190328_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoltype',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
