# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0007_protocoltype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='friendlyName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'uploads/packages'),
        ),
        migrations.AlterField(
            model_name='protocoltype',
            name='icon',
            field=models.ImageField(blank=True, upload_to=b'uploads/prot-types'),
        ),
    ]
