# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0010_auto_20190403_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
