# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0011_auto_20190404_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'packages'),
        ),
        migrations.AlterField(
            model_name='protocoltype',
            name='icon',
            field=models.ImageField(blank=True, upload_to=b'prot-types'),
        ),
    ]
