# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0012_auto_20190516_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='prot_count',
            field=models.IntegerField(default=0),
        ),
    ]
