# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0013_workflow_prot_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='scipion_version',
            field=models.CharField(default='2.0', max_length=20),
        ),
    ]
