# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-30 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


def migrate_workflows_2_installations(apps, schema_editor):
    workflow = apps.get_model("report_protocols", "Workflow")
    installation = apps.get_model("report_protocols", "Installation")

    currentInstallation = None

    for workflow in workflow.objects.all().order_by('client_ip'):
        # copy data to Installations
        # If installation exists
        if currentInstallation is None or not currentInstallation.client_ip == workflow.client_ip:
            currentInstallation = installation.objects.create()
            currentInstallation.client_ip = workflow.client_ip
            currentInstallation.creation_date = workflow.date
            currentInstallation.lastSeen = workflow.lastModificationDate
            currentInstallation.client_address = workflow.client_address
            currentInstallation.client_country = workflow.client_country
            currentInstallation.client_city = workflow.client_city
            currentInstallation.save()

        workflow.installation = currentInstallation
        workflow.save()


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0014_workflow_scipion_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('lastSeen', models.DateTimeField(default=datetime.datetime.now)),
                ('client_ip', models.GenericIPAddressField(null=True)),
                ('client_address', models.CharField(max_length=256, null=True)),
                ('client_country', models.CharField(max_length=256, null=True)),
                ('client_city', models.CharField(max_length=256, null=True)),
                ('scipion_version', models.CharField(default='2.0', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['friendlyName', 'name']},
        ),
        migrations.AddField(
            model_name='workflow',
            name='installation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_protocols.Installation'),
        ),
        # Migrate dta from workflows to installations
        migrations.RunPython(migrate_workflows_2_installations, reverse_code=migrations.RunPython.noop),

    ]
