# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-30 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0015_auto_20201130_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='client_city',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='client_country',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='client_ip',
        ),
    ]
