# Generated by Django 4.0 on 2025-02-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0016_auto_20201130_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='logo',
            field=models.ImageField(blank=True, upload_to='packages'),
        ),
        migrations.AlterField(
            model_name='protocoltype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='prot-types'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='project_uuid',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.CreateModel(
            name='NextProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('next_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_protocol', to='report_protocols.protocol')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_protocol', to='report_protocols.protocol')),
            ],
        ),
    ]
