# Generated by Django 4.0 on 2025-02-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_protocols', '0017_alter_package_logo_alter_protocoltype_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextprotocol',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_protocol', to='report_protocols.protocol'),
        ),
    ]
