# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=256)),
                ('organization', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('subscription', models.BooleanField()),
                ('country', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=16)),
                ('platform', models.CharField(max_length=256)),
            ],
        ),
    ]
