# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='size',
            field=models.CharField(default='10 MB', max_length=256),
            preserve_default=False,
        ),
    ]
