# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_download_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ('creation',)},
        ),
    ]
