# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180210_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('dirName', models.CharField(max_length=256)),
                ('pipName', models.CharField(blank=True, max_length=256, null=True)),
                ('pluginSourceUrl', models.CharField(blank=True, max_length=500, null=True)),
                ('binaryVersions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('pluginVersions', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
