# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180312_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='dirName',
            field=models.CharField(help_text='string pls', max_length=256, verbose_name='name of the module in the pip package'),
        ),
    ]
