# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180504_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bundles/')),
                ('version', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=256)),
                ('size', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deprecated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='download',
            name='email',
        ),
        migrations.RemoveField(
            model_name='download',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='download',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='download',
            name='subscription',
        ),
        migrations.AddField(
            model_name='download',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='country',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
