# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190328_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='file',
            field=models.FileField(upload_to=b'uploads/bundles'),
        ),
    ]
