# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190506_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='client_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='file',
            field=models.FileField(upload_to=b'bundles'),
        ),
    ]
