# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190506_1634'),
        ('web', '0010_auto_20190506_1326'),
    ]

    operations = [
    ]
