# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 15:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180312_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='pluginVersions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
