# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190516_1008'),
        ('web', '0011_merge_20190510_2020'),
    ]

    operations = [
    ]
