# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180312_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='binaryVersions',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='dirName',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='pluginSourceUrl',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='pluginVersions',
        ),
    ]
