# Generated by Django 4.0 on 2025-02-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_merge_20190516_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundle',
        ),
        migrations.DeleteModel(
            name='Download',
        ),
    ]
