# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180410_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='pipName',
            field=models.CharField(default='pipname', help_text='name of the plugin in pip repository', max_length=256),
            preserve_default=False,
        ),
    ]
