# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 21:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField(default=300)),
                ('sample', models.CharField(max_length=128)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dose', models.FloatField()),
                ('pixelsize', models.FloatField(choices=[(1.0, '1'), (3.0, '3')], default=3.0)),
            ],
        ),
        migrations.CreateModel(
            name='Microscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('detector', models.CharField(max_length=64, unique=True)),
                ('detectorPixelSize', models.FloatField(default=14)),
                ('cs', models.FloatField(default=2.7)),
            ],
        ),
        migrations.CreateModel(
            name='ScipionBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFolder', models.CharField(default='/home/scipionuser/OffloadData', max_length=256)),
                ('data_backup', models.CharField(default='/media/scipionuser', max_length=256)),
                ('pattern', models.CharField(default='GRID_??/DATA/Images-Disc?/GridSquare_*/Data/FoilHole_                                         *frames.mrc', max_length=256)),
                ('html_publish', models.CharField(default='rsync -av %(REPORT_FOLDER)s scipionbox@nolan:/home/scipionbox/public_html/', max_length=256)),
                ('email_notification', models.BooleanField(default=False)),
                ('smtp_server', models.CharField(default='localhost', max_length=256)),
                ('smtp_from', models.CharField(default='noreply-biocomp@cnb.csic.es', max_length=256)),
                ('smtp_to', models.CharField(default='user@domain', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('workflow', models.TextField(unique=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='acquisition',
            name='microscope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_proj.Microscope'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_proj.Workflow'),
        ),
    ]
