# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='pixelsize',
        ),
        migrations.AddField(
            model_name='scipionbox',
            name='name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='microscope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='create_proj.Microscope'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='voltage',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='create_proj.Workflow'),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='detector',
            field=models.CharField(default='FalconIII', max_length=64, unique=True),
        ),
    ]
