# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0002_auto_20171016_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scipionbox',
            name='dataFolder',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='projname',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microscope',
            name='dataFolder',
            field=models.CharField(default='/home/scipionuser/OffloadData', max_length=256),
        ),
    ]
