# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0003_auto_20171016_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='backupPath',
            field=models.FilePathField(blank=True),
        ),
    ]
