# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0005_auto_20171016_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='backupPath',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/'),
        ),
    ]
