# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0006_auto_20171017_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition2',
            fields=[
                ('acquisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='create_proj.Acquisition')),
                ('dose', models.FloatField()),
                ('pixelsize', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='backupPath',
            field=models.FilePathField(allow_files=False, allow_folders=True, path=b'/media/roberto'),
        ),
    ]
