# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0007_auto_20171017_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition2',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='acquisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_proj.Acquisition'),
        ),
    ]
