# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0008_auto_20171017_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition2',
            old_name='dose',
            new_name='dose_per_pixel',
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='autofocus',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='c2',
            field=models.IntegerField(choices=[(30, '30'), (50, '50'), (70, '70'), (150, '150')], default=50),
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='delay_after_image_shift',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='delay_after_stage_shift',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='drift_meassurement',
            field=models.CharField(choices=[('never', 'never'), ('always', 'always'), ('gridsquare', 'gridsquare')], default='never', max_length=16),
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='exposure_hole',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='frames_in_fraction',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='illuminated_area',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='max_image_shift',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='nominal_defocus_max',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='nominal_defocus_min',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='nominal_magnification',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='number_of_fractions',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='o1',
            field=models.IntegerField(choices=[(30, '30'), (70, '70')], default=70),
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='php',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=3),
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='spotsize',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='total_exposure_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='projname',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
