# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0009_auto_20171017_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='projname',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
