# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0010_auto_20171017_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='backupPath',
            field=models.FilePathField(allow_files=False, allow_folders=True, path=b'/run/media/roberto'),
        ),
    ]
