# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0011_auto_20171017_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition2',
            old_name='dose_per_pixel',
            new_name='dose_per_frame',
        ),
        migrations.RenameField(
            model_name='acquisition2',
            old_name='pixelsize',
            new_name='sampling_rate',
        ),
    ]
