# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0012_auto_20171017_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='schedule',
            field=models.BooleanField(default=False),
        ),
    ]
