# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0013_acquisition_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScipionBox',
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='backupPath',
            field=models.CharField(default='NOBACKUP', max_length=128),
        ),
    ]
