# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0014_auto_20171018_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='backupPath',
            field=models.CharField(blank=True, default='NOBACKUP', max_length=128),
        ),
    ]
