# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proj', '0015_auto_20171018_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition2',
            old_name='autofocus',
            new_name='autofocus_distance',
        ),
        migrations.RemoveField(
            model_name='acquisition2',
            name='nominal_defocus_max',
        ),
        migrations.RemoveField(
            model_name='acquisition2',
            name='nominal_defocus_min',
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='dose_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition2',
            name='nominal_defocus',
            field=models.CharField(blank=True, default='array of floats', max_length=128),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='delay_after_stage_shift',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='illuminated_area',
            field=models.FloatField(blank=True, default=1.68),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='max_image_shift',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='acquisition2',
            name='php',
            field=models.IntegerField(choices=[(0, '--'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=3),
        ),
    ]
